version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webshop-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webshop-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "82:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb
    container_name: webshop-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  phpmyadmin:
    container_name: webshop-phpmyadmin
    image: phpmyadmin
    ports:
      - 10002:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=webshop-db
    depends_on:
      - db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
